name: daily_update
on:
  schedule:
    # 日本時間で毎日午前 6 時に実行
    - cron: "0 21 * * *"
  workflow_dispatch: # 手動でのトリガーも可能にする

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.32.2

      - name: Run script and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          python add_new_data.py
          git add index.html
          git add data
          git commit -m "daily update"
          git pull
          git push origin main
        env:
          TZ: "Asia/Tokyo"
